project:
  type: website

website:
  title: "Second-hand Fashion AI"
  navbar:
    background: "#2C3E50"
    foreground: "#ECF0F1"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      # - href: posts/
      #   text: Posts

format:
  html:
    theme:
      light: [default, custom.scss]
    css: styles.css
    toc: true
