project:
  type: website

website:
  title: "Second-hand Fashion AI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
format:
  html:
    theme:
      light: [default, custom.scss]
      dark: [darkly, custom.scss]
    toc: false
