project:
  type: website

website:
  title: "AI for second-hand fashion"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd 
        text: Posts
    right:
      - icon: github
        href: https://github.com/fnauman
      - icon: linkedin
        href: https://www.linkedin.com/in/fnauman/
      - icon: envelope
        aria-label: email
        href: "mailto:farrukh.nauman@ri.se"  
      - icon: web
        href: https://fnauman.github.io/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



